
zuul:
  prefix: /api
  ignored-services: '*' # 排除所有基于Eureka服务ID的路由的注册
  routes:
    customer:
      path: '/customer/**'
#      service-id: customer
      url: http://localhost:8128
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 5000

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000
#
#ribbon:
#  ReadTimeout: 5000
#
#eureka:
#  client:
#    serviceURL:
#      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true

ribbon:
  eureka:
    enabled: false


server:
  port: ${ZUUL_PORT:8080}

logging:
  level:
    com.example.store: DEBUG


