#zuul:
#  routes:
#    customer:
#      url: http://localhost:8280
#    preference:
#      url: http://localhost:8180
#    recommendation:
#      url: http://localhost:8380

#ribbon:
#  eureka:
#    enabled: false

zuul:
  prefix: /api
  ignored-services: '*' # 排除所有基于Eureka服务ID的路由的注册
  routes:
    customer:
      path: '/customer/**'
      service-id: customer

eureka:
  client:
    serviceURL:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true



server:
  port: 8080

logging:
  level:
    com.example.store: DEBUG
